baseURL = "https://aviadhaham.me"
relativeURLs = false
languageCode = "en-us"
copyright = "© 2024 Aviad Haham. All rights reserved."
title = "aviadhaham.me"
theme = "risotto"
enableRobotsTXT = true

[params.theme]
palette = "tokyo-night-dark"

[[menu.main]]
identifier = "nuggets"
name = "nuggets"
title = "nuggets"
url = "/nuggets"

[[menu.main]]
identifier = "blog"
name = "blog"
title = "blog"
url = "/posts"

[[menu.main]]
identifier = "projects"
name = "projects"
title = "projects"
url = "/projects"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/aviadhaham"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/aviadhaham"
